PREFIX enrepo: <http://ont.enapso.com/repo#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
#SPARQL query to copy the givens data property name to the label of each individual of a class
insert {
      ?environment rdfs:label ?label.
	     }
where { 
      ?environment a enrepo:Environment.
      ?environment enrepo:name ?name.
      bind(strlang(?name,"en") as ?label)
      }